@startuml
'Fonctionnalite 5 et 6 : Perte et reset superviseur moniteur

skinparam monochrome true

start
:Connexion_etablie?;
:Ouvrir_Socket?;
:err=Comonitor.read();
while (err) is (!message_monitor_lost)
    :Ouvrir_Socket?;
    :err=Comonitor.read();
endwhile (message_monitor_lost)
:Stopper Robot;
:ComMonitor.Close;
:Deconnecter Robot;
:Deconnecter Camera;
stop
@enduml
